---
title: "p_trust"
output: html_document
date: "2023-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis script for "

```{r load libraries}
library(readr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(stats)
library(lme4)
library(dplyr)
library(ez)
library(ltm)
```


## Extract dataframe from csv file and get (mean, sd) or (mean, se) summary

```{r read csv}

setwd("C:/Users/micha/OneDrive/My_GitHub_Repos/HRI/studies_combined/")
data_df <- read_csv("sliced_combined_data.csv")


######################### get mean and sd (or se) ######################### 
data_df %>%
  group_by(autonomy, noisy_robot) %>%
  get_summary_stats(tapping_err_short, type = "mean_sd")

```

## Plots

```{r do plotting}

######################### cool box plot (courtesy of Sarah) ######################### 
ggplot(data_df,aes(x=noisy_robot,y=tapping_err_short, fill=noisy_robot))+geom_boxplot(aes(fill=noisy_robot)) + labs( x = "noisy_robot", y = "tapping_err_short", fill = "noisy_robot") +   theme_minimal() +
# stat_summary(fun = mean, geom = "point",size = 3, shape = 2, position = position_dodge(0.75), show.legend = FALSE) +
scale_fill_brewer(palette = "Set2") +
    theme(plot.title = element_text(size = 15, face = "bold"),
        axis.title.x = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold"),
        axis.text = element_text(size = 16),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 11),
        legend.position= "none") +
  facet_grid(. ~ autonomy) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text.x = element_text(angle = 0, hjust = 0.5, size = 12), legend.position = "none")


######################### cool box plot (courtesy of Sarah) ######################### 
ggplot(data_df,aes(x=noisy_robot,y=tapping_err_long, fill=noisy_robot))+geom_boxplot(aes(fill=noisy_robot)) + labs( x = "noisy_robot", y = "tapping_err_long", fill = "noisy_robot") +   theme_minimal() +
# stat_summary(fun = mean, geom = "point",size = 3, shape = 2, position = position_dodge(0.75), show.legend = FALSE) +
scale_fill_brewer(palette = "Set2") +
    theme(plot.title = element_text(size = 15, face = "bold"),
        axis.title.x = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold"),
        axis.text = element_text(size = 16),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 11),
        legend.position= "none") +
  facet_grid(. ~ autonomy) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text.x = element_text(angle = 0, hjust = 0.5, size = 12), legend.position = "none")


######################### cool box plot (courtesy of Sarah) ######################### 
ggplot(data_df,aes(x=noisy_robot,y=tapping_err_ave, fill=noisy_robot))+geom_boxplot(aes(fill=noisy_robot)) + labs( x = "noisy_robot", y = "tapping_err_ave", fill = "noisy_robot") +   theme_minimal() +
# stat_summary(fun = mean, geom = "point",size = 3, shape = 2, position = position_dodge(0.75), show.legend = FALSE) +
scale_fill_brewer(palette = "Set2") +
    theme(plot.title = element_text(size = 15, face = "bold"),
        axis.title.x = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold"),
        axis.text = element_text(size = 16),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 11),
        legend.position= "none") +
  facet_grid(. ~ autonomy) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text.x = element_text(angle = 0, hjust = 0.5, size = 12), legend.position = "none")

```


```{r do plotting}

bxp <- ggboxplot(
  data_df, x = "auto_grouped", y = "tapping_err_short",
  color = "order", palette = "jco",
  facet.by = "noisy_robot",
  ylim = c(-10, 20), add = "jitter"
  )
bxp

bxp <- ggboxplot(
  data_df, x = "auto_grouped", y = "tapping_err_short",
  color = "noisy_robot", palette = "jco",
  ylim = c(-10, 20), add = "jitter"
  )
bxp

```


## Check assumptions

```{r check assumptions}

######################### check for outliers ######################### 
data_df %>%
  group_by(noisy_robot, order, auto_grouped) %>%
  identify_outliers(tapping_err_short)

######################### Shapiro-Wilk test for normality ######################### 
data_df %>%
  group_by(noisy_robot, order, auto_grouped) %>%
  shapiro_test(tapping_err_short)

ggqqplot(data_df, "tapping_err_short", ggtheme = theme_bw()) + facet_grid(auto_grouped ~ noisy_robot, labeller = "label_both")

######################### check variance homogeneity ######################### 
data_df %>%
  group_by(auto_grouped) %>%
  levene_test(tapping_err_short ~ noisy_robot*order)

```


## Fit Model

```{r fit model}

######################### Three-way mixed ANOVA test #########################  
res.aov <- anova_test(data = data_df, dv = tapping_err_short, wid = pid, within = auto_grouped, between = c(noisy_robot, order))
anova_per_auto <- get_anova_table(res.aov)
anova_per_auto

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
