---
title: "p_trust"
output: html_document
date: "2023-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis script for "

```{r load libraries}
library(readr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(stats)
library(lme4)
library(dplyr)
library(ez)
library(ltm)
```


## Extract dataframe from csv file and get (mean, sd) or (mean, se) summary

```{r read csv}

setwd("C:/Users/micha/OneDrive/My_GitHub_Repos/HRI/study1_results/")
data_df <- read_csv("all_data.csv")

######################### get mean and sd (or se) ######################### 
data_df %>%
  group_by(autonomy, order) %>%
  get_summary_stats(tlx_mental, type = "mean_sd")

######################### get mean and sd (or se) ######################### 
data_df %>%
  group_by(autonomy, order) %>%
  get_summary_stats(tlx_physical, type = "mean_sd")

######################### get mean and sd (or se) ######################### 
data_df %>%
  group_by(autonomy, order) %>%
  get_summary_stats(tlx_hurried, type = "mean_sd")

######################### get mean and sd (or se) ######################### 
data_df %>%
  group_by(autonomy, order) %>%
  get_summary_stats(tlx_insecure, type = "mean_sd")

######################### get mean and sd (or se) ######################### 
data_df %>%
  group_by(autonomy, order) %>%
  get_summary_stats(tlx_hard, type = "mean_sd")

######################### get mean and sd (or se) ######################### 
data_df %>%
  group_by(autonomy, order) %>%
  get_summary_stats(tlx_successful, type = "mean_sd")


```

## Plots

```{r do plotting}

# ######################### cool box plot (courtesy of Sarah) ######################### 
# ggplot(data_df,aes(x=order,y=tlx_physical, fill=order))+geom_boxplot(aes(fill=order)) + labs( x = "Order", y = "tlx_physical", fill = "Order") +   theme_minimal() +
# # stat_summary(fun = mean, geom = "point",size = 3, shape = 2, position = position_dodge(0.75), show.legend = FALSE) +
# scale_fill_brewer(palette = "Set2") +
#     theme(plot.title = element_text(size = 15, face = "bold"),
#         axis.title.x = element_text(size = 14, face = "bold"),
#         axis.title.y = element_text(size = 14, face = "bold"),
#         axis.text = element_text(size = 16),
#         legend.title = element_text(size = 12),
#         legend.text = element_text(size = 11),
#         legend.position= "none") +
#   facet_grid(. ~ autonomy) +
#   theme(axis.text.x = element_text(angle = 45, hjust = 1),
#         strip.text.x = element_text(angle = 0, hjust = 0.5, size = 12), legend.position = "none")
# 
# 
# ######################### cool dot plot ######################### 
# ggplot(data_df,aes(x=order,y=tlx_physical, fill=order)) + geom_boxplot() + geom_dotplot(binaxis='y', stackdir='center', stackratio=1.5, dotsize=1.2) + 
#                     labs( x = "Order", y = "tlx_physical", fill = "Order") + theme_minimal() +
# # stat_summary(fun = mean, geom = "point",size = 3, shape = 2, position = position_dodge(0.75), show.legend = FALSE) +
# scale_fill_brewer(palette = "Set2") +
#     theme(plot.title = element_text(size = 15, face = "bold"),
#         axis.title.x = element_text(size = 14, face = "bold"),
#         axis.title.y = element_text(size = 14, face = "bold"),
#         axis.text = element_text(size = 16),
#         legend.title = element_text(size = 12),
#         legend.text = element_text(size = 11),
#         legend.position= "none") +
#   facet_grid(. ~ autonomy) +
#   theme(axis.text.x = element_text(angle = 45, hjust = 1),
#         strip.text.x = element_text(angle = 0, hjust = 0.5, size = 12), legend.position = "none")


## define custom median function
plot.median <- function(x) {
  m <- median(x)
  c(y = m, ymin = m, ymax = m)
}

## define custom mean function
plot.median <- function(x) {
  m <- mean(x)
  c(y = m, ymin = m, ymax = m)
}

######################### cool dot plot 2 ######################### 
p <- ggplot(data_df,aes(x=order,y=tlx_physical, fill=order)) + geom_dotplot(binaxis='y', stackdir='center', stackratio=1.5, dotsize=0.6) + 
                    labs( x = "Order", y = "NASA-TLX", fill = "Order") + theme_minimal() +
stat_summary(fun.y = mean, geom="crossbar", colour="red", width=0.5, size=0.5) +
scale_fill_brewer(palette = "Set2") +
    theme(plot.title = element_text(size = 15, face = "bold"),
        axis.title.x = element_text(size = 18, face = "bold"),
        axis.title.y = element_text(size = 18, face = "bold"),
        axis.text = element_text(size = 18),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 11),
        legend.position= "none") +
  facet_grid(. ~ auto_grouped, ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text.x = element_text(angle = 0, hjust = 0.5, size = 18), legend.position = "none")

p

# ggexport(p, filename = "pdfs/tlx.pdf")

```


```{r do plotting}

bxp1 <- ggboxplot(
  data_df, x = "autonomy", y = "tlx_mental",
  color = "order", palette = "jco",
  ylim = c(0, 20), add = "jitter"
  )
bxp1

bxp1 <- ggboxplot(
  data_df, x = "autonomy", y = "tlx_physical",
  color = "order", palette = "jco",
  ylim = c(0, 20), add = "jitter"
  )
bxp1

bxp1 <- ggboxplot(
  data_df, x = "autonomy", y = "tlx_hurried",
  color = "order", palette = "jco",
  ylim = c(0, 20), add = "jitter"
  )
bxp1

bxp1 <- ggboxplot(
  data_df, x = "autonomy", y = "tlx_insecure",
  color = "order", palette = "jco",
  ylim = c(0, 20), add = "jitter"
  )
bxp1

bxp1 <- ggboxplot(
  data_df, x = "autonomy", y = "tlx_hard",
  color = "order", palette = "jco",
  ylim = c(0, 20), add = "jitter"
  )
bxp1

bxp1 <- ggboxplot(
  data_df, x = "autonomy", y = "tlx_successful",
  color = "order", palette = "jco",
  ylim = c(0, 20), add = "jitter"
  )
bxp1

```


## Check assumptions

```{r check assumptions}

######################### check for outliers ######################### 
data_df %>%
  group_by(autonomy, order) %>%
  identify_outliers(tlx_physical)

######################### check normality ######################### 
ggqqplot(data_df, "tlx_physical", ggtheme = theme_bw()) + facet_grid(autonomy ~ order)

######################### check variance homogeneity ######################### 
data_df %>%
  group_by(autonomy) %>%
  levene_test(tlx_physical ~ order)

######################### check covariance homogeneity ######################### 
box_m(data_df[, "tlx_physical", drop = FALSE], data_df$order)

```


## Fit Model

```{r fit model}

######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(data = data_df, dv = tlx_physical, wid = pid, between = order, within = autonomy)
anova_tlx_physical <- get_anova_table(res.aov)
anova_tlx_physical


######################### One-way ANOVA test (without order) #########################  
res.aov <- anova_test(data = data_df, dv = tlx_physical, wid = pid, within = autonomy)
anova_tlx_physical <- get_anova_table(res.aov)
anova_tlx_physical


# ######################### SIG 2-WAY INTER: Pairwise comparisons between group levels #########################
# pwc <- data_df %>%
#   group_by(autonomy) %>%
#   pairwise_t_test(tlx_physical ~ order, p.adjust.method = "bonferroni")
# pwc
# 
# ######################### NON-SIG 2-WAY INTER: Pairwise comparisons between group levels #########################
# data_df %>%
#   pairwise_t_test(
#     tlx_physical ~ autonomy, paired = TRUE,
#     p.adjust.method = "bonferroni"
# )
# 
# data_df %>%
#   pairwise_t_test(
#     tlx_physical ~ order, 
#     p.adjust.method = "bonferroni"
#   )

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
