---
title: "p_trust"
output: html_document
date: "2023-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis script for "

```{r load libraries}
library(readr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(stats)
library(lme4)
library(dplyr)
library(ez)
```


## Extract dataframe from csv file and get (mean, sd) or (mean, se) summary

```{r read csv}

setwd("C:/Users/micha/OneDrive/My_GitHub_Repos/HRI/study2_results/")
data_df <- read_csv("sliced_data.csv")

auto_levels_order <- c("high", "low")
data_df$auto_grouped <- factor(data_df$auto_grouped, levels = auto_levels_order)

######################### get mean and sd (or se) ######################### 
data_df %>%
  group_by(autonomy, order) %>%
  get_summary_stats(per_auto, type = "mean_sd")


######################### NASA-TLX ######################### 
p <- ggplot(data_df, aes(x=order, y=per_auto, fill=factor(interaction(order, auto_grouped)))) + 
  geom_dotplot(binaxis='y', stackdir='center', stackratio=1.5, dotsize=1.4) + 
  labs( x = "Order", y = "Perceived Autonomy", fill = "Autonomy Level") + theme_minimal() +
  stat_summary(fun.y = mean, geom="crossbar", colour="red", width=0.5, size=0.7) +
  scale_fill_manual(values=c("#0000CC", "#3399FF", "#006600", "#00CC00")) +
    theme(plot.title = element_text(size = 15, face = "bold"),
        axis.title.x = element_text(size = 28, face = "bold"),
        axis.title.y = element_text(size = 28, face = "bold"),
        axis.text = element_text(size = 24),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 11),
        legend.position= "none") +
  facet_grid(. ~ auto_grouped, ) +
  theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 24, face = "bold"),
        strip.text.x = element_text(angle = 0, hjust = 0.5, size = 28, face = "bold"), legend.position = "none")
p


```

## Plots

```{r do plotting}

######################### cool box plot (courtesy of Sarah) ######################### 
ggplot(data_df,aes(x=order,y=per_auto, fill=order))+geom_boxplot(aes(fill=order)) + labs( x = "Order", y = "per_auto", fill = "Order") +   theme_minimal() +
# stat_summary(fun = mean, geom = "point",size = 3, shape = 2, position = position_dodge(0.75), show.legend = FALSE) +
scale_fill_brewer(palette = "Set2") +
    theme(plot.title = element_text(size = 15, face = "bold"),
        axis.title.x = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold"),
        axis.text = element_text(size = 16),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 11),
        legend.position= "none") +
  facet_grid(. ~ autonomy) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text.x = element_text(angle = 0, hjust = 0.5, size = 12), legend.position = "none")


######################### scatterplot ######################### 
ggplot(data_df, aes(x=autonomy, y=per_auto)) + 
    geom_point()


```

```{r do plotting}

bxp1 <- ggboxplot(
  data_df, x = "auto_grouped", y = "per_auto",
  color = "order", palette = "jco",
  ylim = c(0, 10), add = "jitter"
  )
bxp1

```

## Check assumptions

```{r check assumptions}

######################### check for outliers ######################### 
data_df %>%
  group_by(autonomy, order) %>%
  identify_outliers(per_auto)

######################### check normality #########################
ggqqplot(data_df, "per_auto", ggtheme = theme_bw()) + facet_grid(autonomy ~ order)

######################### check variance homogeneity ######################### 
data_df %>%
  group_by(autonomy) %>%
  levene_test(per_auto ~ order)

######################### check covariance homogeneity ######################### 
box_m(data_df[, "per_auto", drop = FALSE], data_df$order)

```


## Fit Model

```{r fit model}


######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(data = data_df, dv = per_auto, wid = pid, between = order, within = autonomy)
anova_per_auto <- get_anova_table(res.aov)
anova_per_auto


######################### one-way ANOVA test (without order) #########################  
res.aov <- anova_test(data = data_df, dv = per_auto, wid = pid, within = autonomy)
anova_per_auto <- get_anova_table(res.aov)
anova_per_auto


# ######################### SIG 2-WAY INTER: Pairwise comparisons between group levels #########################  
# pwc <- data_df %>%
#   group_by(autonomy) %>%
#   pairwise_t_test(per_auto ~ order, p.adjust.method = "bonferroni")
# pwc
# 
# ######################### NON-SIG 2-WAY INTER: Pairwise comparisons between group levels #########################
# data_df %>%
#   pairwise_t_test(
#     per_auto ~ autonomy, paired = TRUE, 
#     p.adjust.method = "bonferroni"
#   )
# 
# data_df %>%
#   pairwise_t_test(
#     per_auto ~ order, 
#     p.adjust.method = "bonferroni"
#   )

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
